import Testing
import Foundation
import RecapCore
@testable import SemanticKit

/// Coverage for the --changelog target: the prompt structure, the HTML-only
/// behavior, the skill-mode envelope's instruction, and the rendered page.
@Suite("Changelog target")
struct ChangelogTargetTests {
    private let range = ChangeRange(
        base: "v0.1.1", head: "v0.2.0",
        baseSHA: "abcdef1", headSHA: "1234567",
        mergeBaseSHA: "abcdef1")

    private func report() -> ChangeReport {
        let files = [
            FileChange(path: "Sources/SemanticKit/HTMLRender.swift",
                       insertions: 200, deletions: 0, status: "A"),
        ]
        let commits = [
            Commit(sha: "a1b2c3d", shortSHA: "a1b2c3d",
                   authorName: "Ada", authorEmail: "ada@example.com",
                   date: Date(timeIntervalSince1970: 0),
                   subject: "feat: --html renders any command to HTML",
                   type: .feat, scope: nil,
                   breaking: false, isMerge: false, ticket: nil),
        ]
        let vitals = Vitals(
            features: 1, fixes: 0, chores: 0, filesChanged: 1,
            insertions: 200, deletions: 0,
            contributors: [], branchCount: 1, hotspots: files)
        return ChangeReport(
            range: range, commits: commits, files: files, branches: [],
            vitals: vitals, riskFlags: [])
    }

    // MARK: - Target metadata

    @Test("changelog is HTML-only and doesn't require a product")
    func metadata() {
        #expect(NoteTarget.changelog.isHTMLOnly)
        #expect(!NoteTarget.changelog.requiresProduct)
        // Other targets stay text-by-default; we're not changing their shape.
        #expect(!NoteTarget.pr.isHTMLOnly)
        #expect(!NoteTarget.ascUpdate.isHTMLOnly)
    }

    @Test("changelog has no hard ceiling — it's not store-bound")
    func uncapped() {
        let limits = ReviewNoteLimits.fallback
        #expect(limits.ceiling(for: .changelog, platform: .iOS) == 0)
        #expect(limits.ceiling(for: .changelog, platform: .android) == 0)
    }

    @Test("changelog has a default soft target so the page stays scannable")
    func defaultSoftTarget() {
        // No product profile → still 1500 (a sensible default for a release page).
        let profile = ProductProfile(
            id: "x", name: "X", voice: "v", links: [],
            platform: .iOS, targets: [:])
        #expect(profile.softTarget(for: .changelog) == 1500)
        // An explicit target overrides the default.
        let custom = ProductProfile(
            id: "y", name: "Y", voice: "v", links: [],
            platform: .iOS, targets: ["changelog": 800])
        #expect(custom.softTarget(for: .changelog) == 800)
    }

    // MARK: - Prompt

    @Test("changelog prompt asks for Added / Changed / Fixed sections")
    func prompt() {
        let req = PromptBuilder.note(
            report(), target: .changelog, product: nil,
            limit: ResolvedLimit(ceiling: 0, softTarget: 1500))
        #expect(req.system.contains("## Added"))
        #expect(req.system.contains("## Changed"))
        #expect(req.system.contains("## Fixed"))
        // Should explicitly exclude noise.
        #expect(req.system.contains("dependency"))
        #expect(req.system.contains("commit hashes"))
    }

    // MARK: - Skill envelope

    @Test("skill envelope tells the agent to write markdown sections, not HTML")
    func skillEnvelope() {
        let envelope = SkillEnvelope.forNote(
            report(), target: .changelog, product: nil,
            limit: ResolvedLimit(ceiling: 0, softTarget: 1500))
        #expect(envelope.target == "changelog")
        // rw wraps the response — the agent should NOT return HTML.
        #expect(envelope.instruction.lowercased().contains("markdown"))
        #expect(envelope.instruction.contains("## Added"))
        #expect(envelope.instruction.contains("rw will wrap"))
    }

    // MARK: - HTML render

    @Test("changelog HTML uses the version label as the page title")
    func htmlTitle() {
        let prose = """
        ## Added
        - New --html flag.

        ## Changed
        - GUIDE moved to repo root.
        """
        let html = HTMLRender.changelog(prose, version: "v0.2.0", range: range)
        #expect(html.contains("<h1>v0.2.0</h1>"))
        #expect(html.contains("Changelog · v0.1.1…v0.2.0"))
        #expect(html.contains("<h2>Added</h2>"))
        #expect(html.contains("<li>New --html flag.</li>"))
        #expect(html.contains("<h2>Changed</h2>"))
    }

    @Test("changelog HTML carries a 'generated by rw' credit")
    func footnote() {
        let html = HTMLRender.changelog(
            "## Added\n- thing.", version: "v0.2.0", range: range)
        #expect(html.contains("Generated by"))
        #expect(html.contains("rw notes --changelog"))
        #expect(html.contains("https://novarch.lol/recap-wins"))
    }

    @Test("changelog HTML escapes hostile prose")
    func escaping() {
        let html = HTMLRender.changelog(
            "## Added\n- <evil> & \"quoted\".", version: "v0.2.0", range: range)
        #expect(html.contains("&lt;evil&gt; &amp; &quot;quoted&quot;."))
        #expect(!html.contains("<evil>"))
    }

    @Test("changelog has no cap meter (it's not store-bound)")
    func noCapMeter() {
        let html = HTMLRender.changelog(
            "## Added\n- thing.", version: "v0.2.0", range: range)
        #expect(!html.contains("class=\"meter"))
        #expect(!html.contains("class=\"bar"))
    }

    @Test("changelog HTML handles empty / minimal prose without crashing")
    func minimalProse() {
        let html = HTMLRender.changelog("", version: "v0.0.1", range: range)
        #expect(html.contains("<h1>v0.0.1</h1>"))
        // Still a complete document.
        #expect(html.contains("<!doctype html>"))
        #expect(html.contains("</html>"))
    }

    @Test("changelog renders **bold** and `code` inline spans")
    func inlineMarkdown() {
        let html = HTMLRender.changelog(
            "## Added\n- **Headline.** Body with `code` and a `path/file`.",
            version: "v0.2.0", range: range)
        #expect(html.contains("<strong>Headline.</strong>"))
        #expect(html.contains("<code>code</code>"))
        #expect(html.contains("<code>path/file</code>"))
        // No literal markdown markers leaked through.
        #expect(!html.contains("**Headline.**"))
    }

    @Test("an unmatched trailing ** is left as literal text, not an open tag")
    func inlineMarkdownLenient() {
        let html = HTMLRender.changelog(
            "## Added\n- A claim** with a stray marker.",
            version: "v0.2.0", range: range)
        // Should not produce an unclosed <strong>.
        #expect(!html.contains("<strong>"))
        #expect(html.contains("A claim** with a stray marker."))
    }

    /// Release-generation helper: when `RW_CHANGELOG_OUT` is set in the env,
    /// reads markdown prose from the file named by `RW_CHANGELOG_PROSE_FILE`,
    /// wraps it with `HTMLRender.changelog` under the version label
    /// `RW_CHANGELOG_VERSION`, and writes the HTML to the out path. The
    /// assertion only runs when those env vars are set, so normal test runs
    /// are unaffected. Drives `scripts/render-changelog.sh` — the canonical
    /// path for producing `docs/changelogs/vX.Y.Z.html` in skill mode
    /// (see RELEASING.md).
    @Test("emit changelog HTML when RW_CHANGELOG_OUT is set")
    func emitChangelog() throws {
        let env = ProcessInfo.processInfo.environment
        guard let out = env["RW_CHANGELOG_OUT"], !out.isEmpty,
              let proseFile = env["RW_CHANGELOG_PROSE_FILE"], !proseFile.isEmpty else {
            return
        }
        let version = env["RW_CHANGELOG_VERSION"] ?? "v0.0.0"
        let prose = try String(contentsOfFile: proseFile, encoding: .utf8)
        // Use a stub range — the prose carries the real story; the range line
        // is only there so the subtitle reads naturally.
        let r = ChangeRange(
            base: env["RW_CHANGELOG_BASE"] ?? "previous",
            head: version,
            baseSHA: "0000000", headSHA: "0000000", mergeBaseSHA: "0000000")
        let html = HTMLRender.changelog(prose, version: version, range: r)
        try html.write(toFile: out, atomically: true, encoding: .utf8)
    }
}
